### ISSUE TITLE
Standard observables?

### ISSUE THREAD

**Issue by brodybits** [ismail-codar/fjsx#3]
I suspect that if this project would use standard observable variables there would be much less JSX transformation needed, and it would be much easier for developers to use alternatives such as Hyperscript, [hyperx](https://github.com/choojs/hyperx), [dscript](https://github.com/dustinspecker/dscript), etc. This is what I requested on Surplus in <https://github.com/adamhaile/surplus/issues/40>.

There is a nice writeup of observables at <https://medium.com/@benlesh/learning-observable-by-building-observable-d5da57405d87>. As an alternative, using [xstream](http://staltz.github.io/xstream/) instead of standard observables would probably make it easier for this project to work with [CycleJS](https://cycle.js.org/).

**Comment by ismail-codar** [comment]
Hi @brodybits . Entegration with reactive programming libraries was already a planned feature.
I did some experiments. (implementing https://github.com/cujojs/most#simple-example) 
* [Example 1](https://github.com/ismail-codar/fjsx/blob/master/packages/fjsx-examples/examples/sum/_.demo.tsx) is fjsx way without any other library.
* [Example 2](https://github.com/ismail-codar/fjsx/blob/master/packages/fjsx-examples/examples/sum-mostjs-1/_.demo.tsx) is uses mostjs with fromEvent
* Finally [Example 3](https://github.com/ismail-codar/fjsx/blob/master/packages/fjsx-examples/examples/sum-mostjs-2/_.demo.tsx) is uses mostjs with newly implemented fjsx.toObservable method.

I think xstream entegration can be work via http://staltz.github.io/xstream/#fromObservable like example 3 
```js 
import xs from 'xstream'
var xStream = xs.fromObservable(fjsx.toObservable(xValue$))
.....
```

**Comment by brodybits** [comment]
Thanks, examples definitely look nice. I will take a closer look when I get a chance (could be a few weeks, if not months).

**Comment by ismail-codar** [comment]
Fjsx is deprecated so please use [fidan](https://github.com/ismail-codar/fidan)
